# .streamlit/config.toml

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[server]
maxUploadSize = 200
maxMessageSize = 200

[browser]
gatherUsageStats = false